import { useNavigate } from "react-router-dom";
import { useEffect } from "react";
import AOS from "aos";
import "aos/dist/aos.css";

const Home = () => {
  const navigate = useNavigate();

  useEffect(() => {
    AOS.init({ duration: 800, once: true });
  }, []);

  return (
    <div className="min-h-screen flex flex-col bg-gradient-to-br from-background via-white to-background">
      <nav className="flex justify-between items-center px-8 py-4">
        <h1 className="text-2xl font-extrabold text-primary">NestoraPrep</h1>
        <button
          onClick={() => navigate("/select-role")}
          className="bg-primary text-white font-bold px-5 py-2 rounded-full hover:bg-primary-dark transform hover:scale-105 transition-all duration-300"
        >
          Start
        </button>
      </nav>

      <div className="flex-grow flex flex-col justify-center items-center text-center px-6">
        <h1
          className="text-5xl md:text-6xl font-extrabold text-darkslate leading-tight mb-6"
          data-aos="fade-up"
        >
          Ace Your <span className="text-primary">Interviews</span> with AI 🚀
        </h1>
        <p
          className="text-lg text-gray-700 max-w-xl mb-8"
          data-aos="fade-up"
          data-aos-delay="200"
        >
          Get role-specific, real-world interview questions generated by OpenAI.
          Prepare smarter, not harder!
        </p>
        <button
          onClick={() => navigate("/select-role")}
          className="bg-primary text-white font-bold px-8 py-3 rounded-full text-lg hover:bg-primary-dark transform hover:scale-105 transition-all duration-300 shadow-lg"
          data-aos="fade-up"
          data-aos-delay="400"
        >
          Start Preparation
        </button>
      </div>

      <footer className="text-center text-gray-400 text-sm py-6">
        © {new Date().getFullYear()} NestoraPrep. Powered by React + OpenAI.
      </footer>
    </div>
  );
};

export default Home;
