import { useNavigate } from "react-router-dom";
import Navbar from "../components/Navbar";

const Home = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen flex flex-col bg-gradient-to-br from-primary via-secondary to-accent">
      <Navbar />
      <div className="flex flex-1 flex-col items-center justify-center text-center p-6">
        <h1 className="text-5xl md:text-6xl font-extrabold text-darkslate mb-6 drop-shadow-lg">
          Ace Your Interviews with AI 🚀
        </h1>
        <p className="text-lg md:text-xl text-darkslate/70 max-w-2xl mb-10">
          Get role-specific, real-world interview questions generated by OpenAI. Prepare smarter, not harder!
        </p>
        <button
          onClick={() => navigate("/select-role")}
          className="bg-darkslate hover:bg-primary text-white font-bold py-3 px-8 rounded-lg shadow-lg transition duration-300"
        >
          Start Preparation
        </button>
      </div>

      <footer className="py-4 text-center text-darkslate/60 text-sm">
        © 2025 NestoraPrep. Powered by React + OpenAI.
      </footer>
    </div>
  );
};

export default Home;